### PR TITLE
Rename exercises

### PR DESCRIPTION
**Pull request by AnnikaLau**

### CODE REVIEW

**Review by mjaehn — CHANGES_REQUESTED** [review]
I would either include `git` in all of the file names or leave it out.

I would prefer to include it, e.g. `Exercise_1_git-log-diff-show.md`

**Comment by AnnikaLau** [comment]
> I would either include `git` in all of the file names or leave it out.
> 
> I would prefer to include it, e.g. `Exercise_1_git-log-diff-show.md`

Better now?

**Comment by mjaehn** [comment]
Let's use `Exercise_8_git-submodule.md` instead of `Exercise_8_git-submodules.md` to reflect the actual git command and we are good to go! 🙌🏻

**Comment by AnnikaLau** [comment]
> Let's use `Exercise_8_git-submodule.md` instead of `Exercise_8_git-submodules.md` to reflect the actual git command and we are good to go! 🙌🏻

Na gut

**Review by mjaehn — APPROVED** [review]
LGTM

**Pull request merged**
