### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by mjaehn**
Fixes https://github.com/C2SM/git-course/issues/90

- [x] Don't use comments within cell blocks
- [x] Unify formatting
- [x] Separate installing Python and JupyterLab  
- [x] Update Windows instructions

### CODE REVIEW

**Comment by mjaehn** [comment]
I want to merge directly into `main` so that we can send out an email to the participants where we refer to the README.

**Comment by AnnikaLau** [comment]
> I want to merge directly into `main` so that we can send out an email to the participants where we refer to the README.

I thought we anyway wait with the email until we merged the revision branch?

**Comment by mjaehn** [comment]
Doesn't that take too long? It would be good if participants have some time to setup their environment. Giving them one week is better than just 1-2 days imho.

**Comment by AnnikaLau** [comment]
> Doesn't that take too long? It would be good if participants have some time to setup their environment. Giving them one week is better than just 1-2 days imho.

well I was planning to merge very soon ;-)

**Comment by AnnikaLau** [comment]
> > Doesn't that take too long? It would be good if participants have some time to setup their environment. Giving them one week is better than just 1-2 days imho.
> 
> well I was planning to merge very soon ;-)

Also, are these small changes here really relevant for the 2 people who would try setting it up more than one day in advance?

**Comment by mjaehn** [comment]
Fine for me if we can merge by the end of the week. 👍🏻

**Review by AnnikaLau — APPROVED** [review]

**Pull request merged**
