### PR TITLE
Update helpers.sh

### PR DESCRIPTION
**Pull request by fabianschoeni**
add a git init to helper function init_repo_empty_schedule

### CODE REVIEW

**Comment by fabianschoeni** [comment]
fixes #95

**Review by AnnikaLau — CHANGES_REQUESTED** [review]
We should delete the cell with `# init Git repository` after `init_repo_empty_schedule` in Exercise 4 with that change.

**Comment by fabianschoeni** [comment]
Oh... that's my bad. I missed that cell... I've been wondering how it hasn't caused bugs in recent years when the git repo hasn't been initialised. But somehow I missed the cell where users are supposed to initialise the repo themselves - sorry! We can leave it as it is.

**Comment by AnnikaLau** [comment]
> Oh... that's my bad. I missed that cell... I've been wondering how it hasn't caused bugs in recent years when the git repo hasn't been initialised. But somehow I missed the cell where users are supposed to initialise the repo themselves - sorry! We can leave it as it is.

I think it's also okay to delete it. Don't know if people really profit from doing it themselves. At least I don't use "git init" much in my daily Git life. I just let you decide ;-)

**Comment by fabianschoeni** [comment]
> > Oh... that's my bad. I missed that cell... I've been wondering how it hasn't caused bugs in recent years when the git repo hasn't been initialised. But somehow I missed the cell where users are supposed to initialise the repo themselves - sorry! We can leave it as it is.
> 
> I think it's also okay to delete it. Don't know if people really profit from doing it themselves. At least I don't use "git init" much in my daily Git life. I just let you decide ;-)

Let's leave it there, that way people have at least seen the git init command once and know it exists.

**Pull request closed without merging**
